# Generated by Django 4.2.29 on 2026-04-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocationprofile',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='userlocationprofile',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
    ]
