# Generated by Django 4.2.29 on 2026-03-14 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=5)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('scooty', 'Scooty')], max_length=10)),
                ('bike_details', models.CharField(max_length=300)),
                ('selected_services', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=15)),
                ('rejection_note', models.TextField(blank=True)),
                ('service_started_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration_min', models.IntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='garages.garage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
