# Generated by Django 4.2.29 on 2026-03-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='garage',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
