# Generated by Django 4.2.29 on 2026-03-18 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0002_alter_garage_latitude_alter_garage_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarageSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('is_open', models.BooleanField(default=True)),
                ('start_hour', models.IntegerField(default=9)),
                ('end_hour', models.IntegerField(default=18)),
                ('interval_minutes', models.IntegerField(default=60)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='garage',
            name='bike_services',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='scooty_services',
        ),
        migrations.AddField(
            model_name='garage',
            name='services',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='curatedservice',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='garage',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='garage',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='garage',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.DeleteModel(
            name='DaySchedule',
        ),
        migrations.AddField(
            model_name='garageschedule',
            name='garage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='garages.garage'),
        ),
        migrations.AlterUniqueTogether(
            name='garageschedule',
            unique_together={('garage', 'day')},
        ),
    ]
