# Generated by Django 4.2.29 on 2026-04-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0003_garageschedule_remove_garage_bike_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='service_prices',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
